apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: hyun
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sus03319@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seunghyun-com-tls
  namespace: hyun
spec:
  secretName: seunghyun-com-tls
  duration: 2160h #90일
  renewBefore: 360h #15일 전에 갱신됨
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.seunghyun.shop
  dnsNames:
  - server.seunghyun.shop

