# 한 pod안에 container가 두개 들어감. pod안에 들어갈 container들은 log나 health체크 같이 의존적인 것들을 넣어야함
apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
  namespace: hyun
  labels:
    app: nginx-busybox-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
      # 위의 nginx container가 살아있는지 health check
  - name: busybox
    image: busybox
    # 같은 pod 내에서는 pod로 바로 호출 가능함 port가 80인 conatiner가 살아있는지!
    command: ['sh', '-c', 'while true; do wget -qO- http://localhost:80; sleep 5; done']
